In [18]:
#Exersice 1

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True

# Promts the user to enter a number
number_input = int(input("Enter a number: "))

# Checks if the number is prime or not and prints the result
if is_prime(number_input):
    print("This is a prime number")
else:
    print("This not a prime number")

This not a prime number


In [23]:
#Exercise 2

def fibonacci(n):
    sequence = [0, 1]
    for _ in range(n - 2):
        sequence.append(sequence[-1] + sequence[-2])
    return sequence[:n]

try:
    num = int(input("Enter how many numbers in Fibonacci sequence to display: "))
    if num < 0:
        print("Please enter a non-negative integer.")
    else:
        print("Fibonacci sequence:", fibonacci(num))
except ValueError:
    print("Invalid input. Please enter an integer.")

Fibonacci sequence: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711]


In [ ]:
#Exercise 3

def print_decreasing_triangle(rows):
    for i in range(rows, 0, -1):
        for j in range(i):
            print("*", end=" ")  
        print() 

#prints the decreasing triangle pattenr
rows = 5
print_decreasing_triangle(rows)


* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
#Exercise 4

def reverse_string():
    user_string = input("Enter a string: ")
    reversed_string = user_string[::-1] 
    print("Reversed string:", reversed_string)

reverse_string()

Reversed string: hdart


In [43]:
#Exercise 5

def find_min_max(numbers):
    if not numbers:
        return None, None

    min_val = min(numbers)
    max_val = max(numbers)
    return min_val, max_val


#because its not stated whether to include or not, this is the code if the user was asked to input the iterable of numbers
#def get_user_numbers():
    numbers = []
    while True:
        try:
            user_input = input("Enter a number (or 'done' to finish): ")
            if user_input.lower() == "done":
                break
            numbers.append(int(user_input))
        except ValueError:
            print("Invalid input. Please enter a number or 'done'.")
    return numbers
#user_numbers = get_user_numbers()


# Find and print min/max
min_result, max_result = find_min_max(user_numbers)

# Example usage with a list:
my_list = [5, 2, 9, 18, 5, 6]
min_result, max_result = find_min_max(my_list)

if min_result is not None and max_result is not None:
    print("Min value is:", min_result)
    print("Max value is:", max_result)

Min value is: 2
Max value is: 18


In [48]:
#Exercise 6

import random

def guess_the_number():
    secret_number = random.randint(1, 10)
    attempts = 0

    while True:
        try:
            guess = int(input("Guess the number (between 1 and 10): "))
            attempts += 1

            if guess < secret_number:
                print("Too low! Try again.")
            elif guess > secret_number:
                print("Too high! Try again.")
            else:
                print(f"Congratulations! You guessed the number {secret_number} correctly in {attempts} attempts!")
                break  # Exit the loop when the guess is correct

        except ValueError:
            print("Invalid input. Please enter an integer.")

if __name__ == "__main__":
    guess_the_number()

#i added number of attempts but i understand it wasnt stated to do so in the exercise promt

Too high! Try again.
Too high! Try again.
Congratulations! You guessed the number 4 correctly in 3 attempts!


In [ ]:
#Exercise 7

def password_checker():
    correct_password = "Big_Data_Applications"

    while True:
        entered_password = input("Enter password: ")

        if entered_password == correct_password:
            print("Access Granted!")
            break 
        else:
            print("Incorrect password. Try again.")

if __name__ == "__main__":
    password_checker()

Incorrect password. Try again.
Access Granted!


In [52]:
#Exercose 8

import math

def calculate_series(x, n):
    total_sum = 0
    for i in range(1, n + 1):
        numerator = x * (5** (2 * i))  # Calculate x * (5^(2*i))
        denominator = i + math.factorial(i + 1)
        total_sum += numerator / denominator
    return total_sum

def main():
    try:
        x = float(input("Enter the value of x: "))
        n = int(input("Enter the number of terms (N): "))

        if n <= 0:
            print("N must be a positive integer.")
            return

        result = calculate_series(x, n)
        print("The sum of the series is:", result)

    except ValueError:
        print("Invalid input. Please enter numeric values for x and N.")

if __name__ == "__main__":
    main()

The sum of the series is: 1912502.5301339012


In [62]:
#Exercise 9

import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import requests
from io import BytesIO

# Load the image from the URL
url = 'https://github.com/H-934/Yr3-BigData/blob/main/CW_PHOTO.jpg?raw=true'
response = requests.get(url)
image = Image.open(BytesIO(response.content))

# Convert to NumPy array
image_array = np.array(image)

# Create mirrored versions
horizontal_mirror = np.fliplr(image_array)  # Flip left to right
vertical_mirror = np.flipud(image_array)    # Flip up to down

# Display original and mirrored images
fig, axes = plt.subplots(1, 3, figsize=(12, 4))

axes[0].imshow(image_array)
axes[0].set_title("Original")
axes[0].axis("off")

axes[1].imshow(horizontal_mirror)
axes[1].set_title("Horizontal Mirror")
axes[1].axis("off")

axes[2].imshow(vertical_mirror)
axes[2].set_title("Vertical Mirror")
axes[2].axis("off")

plt.show()

In [63]:
#Exercise 10

import numpy as np

temperatures_celsius = [22, 24, 19, 21, 23, 25, 26, 27, 24, 23, 20, 22, 21, 19, 18, 22, 23, 24, 26, 28, 30, 27, 25, 26, 24, 22, 21, 20, 19, 23]

# 1) Create a NumPy array
temperatures_np = np.array(temperatures_celsius)

# 2) Find the minimum, maximum, and average temperature
min_temp = np.min(temperatures_np)
max_temp = np.max(temperatures_np)
avg_temp = np.mean(temperatures_np)

print(f"Minimum temperature: {min_temp}°C")
print(f"Maximum temperature: {max_temp}°C")
print(f"Average temperature: {avg_temp:.2f}°C")

# 3) Convert the temperatures from Celsius to Fahrenheit
temperatures_fahrenheit = (temperatures_np * 9/5) + 32
print(f"Temperatures in Fahrenheit: {temperatures_fahrenheit}")

# 4) Find all days where the temperature was above 25°C
days_above_25 = temperatures_np[temperatures_np > 25]
print(f"Days above 25°C: {days_above_25}")

# 5) Count how many days had temperatures below 20°C
days_below_20 = np.sum(temperatures_np < 20)
print(f"Days below 20°C: {days_below_20}")

# 6) Sort the temperature data in ascending order
sorted_temperatures = np.sort(temperatures_np)
print(f"Sorted temperatures: {sorted_temperatures}")

# 7) Reshape the 1D array into a 5x6 2D array
reshaped_temperatures = temperatures_np.reshape(5, 6)
print(f"Reshaped temperatures (5x6):\n{reshaped_temperatures}")

Minimum temperature: 18°C
Maximum temperature: 30°C
Average temperature: 23.13°C
Temperatures in Fahrenheit: [71.6 75.2 66.2 69.8 73.4 77.  78.8 80.6 75.2 73.4 68.  71.6 69.8 66.2
 64.4 71.6 73.4 75.2 78.8 82.4 86.  80.6 77.  78.8 75.2 71.6 69.8 68.
 66.2 73.4]
Days above 25°C: [26 27 26 28 30 27 26]
Days below 20°C: 4
Sorted temperatures: [18 19 19 19 20 20 21 21 21 22 22 22 22 23 23 23 23 24 24 24 24 25 25 26
 26 26 27 27 28 30]
Reshaped temperatures (5x6):
[[22 24 19 21 23 25]
 [26 27 24 23 20 22]
 [21 19 18 22 23 24]
 [26 28 30 27 25 26]
 [24 22 21 20 19 23]]
